title: Caleb Angell | Creative Works
description: Stories from an interconnected universe
baseurl: "/portfolio"

# Build settings
markdown: kramdown
permalink: /blog/:slug/

# Collections
collections:
  chapters:
    output: true
    permalink: /:collection/:path/

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - "*.zip"
