title: Caleb Angell | Creative Works
description: Stories from an interconnected universe
baseurl: "/portfolio"

# Build settings
markdown: kramdown
permalink: /blog/:slug/

# Exclude admin and other files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - "*.zip"
